name: arabic_tajweed_app
description: "Your app description here"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+38

environment:
  sdk: '^3.8.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  get: ^4.6.6
  flutter_svg: ^2.0.9
  figma_squircle: ^0.6.3
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  liquid_glass_widgets: 1.2.1
  path_drawing: ^1.0.1
  xml: ^7.0.1
  json_annotation: ^4.12.0
  collection: ^1.19.1
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  gaimon: ^1.5.0
  audioplayers: ^6.8.1
  audio_waveforms: ^1.3.0
  path_provider: ^2.1.5
  flutter_tilt: ^4.1.0
  tuple: ^2.0.2
  dio: ^5.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.15.1
  json_serializable: ^6.14.1
  drift_dev: ^2.34.5
  sqlite3_flutter_libs: ^0.6.0+eol

flutter:
  uses-material-design: true
  assets:
    - assets/curriculum/
    - assets/audio/
    - assets/svg/
    - assets/svg/alphabet/
    - assets/audio/alphabet/
    - assets/img/
  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest/Onest-Thin.ttf
          weight: 100
        - asset: assets/fonts/Onest/Onest-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Onest/Onest-Light.ttf
          weight: 300
        - asset: assets/fonts/Onest/Onest-Regular.ttf
          weight: 400
        - asset: assets/fonts/Onest/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest/Onest-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Onest/Onest-Bold.ttf
          weight: 700
        - asset: assets/fonts/Onest/Onest-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Onest/Onest-Black.ttf
          weight: 900
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Variable.ttf
    - family: Playfair
      fonts:
        - asset: assets/fonts/Playfair/Playfair-Variable.ttf
    - family: STIXTwoText
      fonts:
        - asset: assets/fonts/STIXTwoText/STIXTwoText-Variable.ttf
        - asset: assets/fonts/STIXTwoText/STIXTwoText-Italic-Variable.ttf
          style: italic
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew/ScheherazadeNew-Regular.ttf
          weight: 400
        - asset: assets/fonts/ScheherazadeNew/ScheherazadeNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ScheherazadeNew/ScheherazadeNew-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ScheherazadeNew/ScheherazadeNew-Bold.ttf
          weight: 700
    - family: DGFaseh
      fonts:
        - asset: assets/fonts/DGFaseh/DG-Faseh-Regular.ttf
          weight: 400
        - asset: assets/fonts/DGFaseh/DG-Faseh-Bold.ttf
          weight: 700
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/JetBrainsMono/JetBrainsMonoNL-ThinItalic.ttf
          style: italic
          weight: 100
